### PR TITLE
#1 Adding additional parameter for max line length

### PR DESCRIPTION
**Pull request by sjaakd**

### CODE REVIEW

**Comment by jtulach** [comment]
Very nice, thanks. Can you please make a note/new paragraph in the readme, so other people find the new feature?

**Comment by sjaakd** [comment]
Done.. 

Any idea when you are going to make a release?

**Comment by jtulach** [comment]
Release 0.8 is [out](http://repo1.maven.org/maven2/org/apidesign/javadoc/codesnippet-doclet/0.8/). I hope it will work for you.

**Comment by sjaakd** [comment]
> Release 0.8 is out. I hope it will work for you.

Works as a breeze!! :+1: ... Thanks a lot for your help!! I'll keep you informed on our progress..

**Pull request merged**
